#cloud-config
users:
  - name: ${ansible_user}
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ${public_key}

packages:
  - python
  - python-pip
  - python-requests
